
version: '3.7'

services:
  django_gunicorn:
    build: ./django
    command: gunicorn mysite.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - static_volume:/usr/src/app/static          
    expose:
      - 8000
    env_file:
      - ./django/.env.prod
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./django/.env.prod.db  
    ports:
      - "5432:5432"
   
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/static        
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn
    
volumes:
  postgres_data:
  static_volume:
 
      
