# Generated by Django 2.2.20 on 2021-05-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='file',
            field=models.FileField(upload_to='main/media/'),
        ),
    ]
