apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1 # tells deployment to run x pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: app-nginx
          image: cecilka1337/django-kubernetes:app-nginx
          command: ["/bin/bash" ,"run.sh"]           
          imagePullPolicy: "Always"
          ports:
            - containerPort: 80
          volumeMounts:
          - name: static-persistent-storage
            mountPath: /var/www/user/static                        
      volumes:
      - name: static-persistent-storage
        persistentVolumeClaim:
          claimName: static-pv-claim
